### ISSUE TITLE
[Feature Request] Hotkeys for moving between frames

### ISSUE THREAD

**Issue by ivanbelyj** [douglasvini/gimp-fanim#3]
Nice plugin! It would be perfect if hotkeys were supported, especially for moving between frames (for example, using arrows). Now this is done using UI buttons, which is not always very convenient

**Comment by douglasvinis** [comment]
Thanks. I tried to implement shortcuts like this back when i was writing the plugin but the API didn't give me ways to capture shortcuts outside the window of the plugin (for example: when i draw in GIMP i would have to click on the plugin window and then push the arrow key to change to the next frame), i then dropped this, since it would not bring any benefit at all. I believe this is still not possible to do but perhaps will be possible in GIMP 3. I hope you understand.
